### ISSUE TITLE
[Feat] Add Apple Silicon or Universal build target for macOS

### ISSUE THREAD

**Issue by HongyuS** [BTMuli/TeyvatGuide#68]
### Issue Check

- [X] 我确认查找过相关的 Issue
- [X] 我确认这个问题是影响使用的
- [X] 我阅读过[提问的艺术](https://github.com/betaseeker/How-To-Ask-Questions)

### 新功能描述

希望能为 macOS 添加 arm64 或通用二进制版本，以提升本应用在现代 Mac 平台的性能。

参考资料：[macOS Bundle / Binary Targets](https://tauri.app/v1/guides/building/macos/#binary-targets)

```
>>> rustup target add aarch64-apple-darwin
>>> tauri build --target universal-apple-darwin
```

### 当前使用版本

v0.3.6

**Comment by HongyuS** [comment]
我在 [tauri-action](https://github.com/tauri-apps/tauri-action) 仓库找到了一个示例，或许能有帮助：[test-action.yml](https://github.com/tauri-apps/tauri-action/blob/dev/.github/workflows/test-action.yml)

这是另一个例子：[release.yml](https://github.com/Synaptrix/ChatGPT-Desktop/blob/master/.github/workflows/release.yml)

看起来只需要给 x86-64 的 macos-latest 额外添加 `aarch64-apple-darwin` 的 rust target，tauri-action 就能自动编译 arm64 版本：
```yaml
      - name: install dependencies (mac only)
        if: matrix.platform == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin
```
